---
###############################################################################
# Pi-Hole DB Configuration
###############################################################################
# DB configuration is optional. DB updates are applied then gravity update is
# run to ensure database ID's are consistent. Apply before UI changes are made
# to ensure consistency.
#
# Reference:
# * https://docs.pi-hole.net/database/

- name: 'db | add adlist source'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_ad_insert }} ({{ item.id }}, \"{{ item.address }}\", {{ item.enabled|int }}, \"{{ item.comment }}\")"'
  become: true
  loop: '{{ pihole_ad_sources }}'
  when: pihole_ad_sources|length > 0

- name: 'db | add domain blocklist'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_domain_insert }} ({{ item.id }}, {{ item.type }}, \"{{ item.domain }}\", {{ item.enabled|int }}, \"{{ item.comment }}\")"'
  become: true
  loop: '{{ pihole_domain_blocklists }}'
  when: pihole_domain_blocklists|length > 0

- name: 'db | add clients'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_client_insert }} ({{ item.id }}, \"{{ item.ip }}\", \"{{ item.comment }}\")"'
  become: true
  loop: '{{ pihole_clients }}'
  when: pihole_clients|length > 0

- name: 'db | add groups'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_groups_insert }} ({{ item.id }}, {{ item.enabled|int }}, \"{{ item.name }}\", \"{{ item.description }}\")"'
  become: true
  loop: '{{ pihole_groups }}'
  when: pihole_groups|length > 0

- name: 'db | add groups ad blocklist'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_ad_groups_insert }} ({{ item.adlist_id }}, {{ item.group_id }})"'
  become: true
  loop: '{{ pihole_ad_groups_blocklist }}'
  when: pihole_ad_groups_blocklist|length > 0

- name: 'db | add groups client blocklist'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_client_groups_insert }} ({{ item.client_id }}, {{ item.group_id }})"'
  become: true
  loop: '{{ pihole_client_groups_blocklist }}'
  when: pihole_client_groups_blocklist|length > 0

- name: 'db | add groups domain blocklist'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_domain_groups_insert }} ({{ item.domainlist_id }}, {{ item.group_id }})"'
  become: true
  loop: '{{ pihole_domain_groups_blocklist }}'
  when: pihole_domain_groups_blocklist|length > 0

- name: 'db | update gravity adlists'
  ansible.builtin.command: 'pihole -g'
  when: not pihole_installed
